### ISSUE TITLE
Replace existing configs

### ISSUE THREAD

**Issue by nebulaw2081d** [tonijarjour/autorice#1]
After viewing the configuration (dotfiles) part of this project, I have determined they are not as through as users of this project are entitled to. The deployment scripts are adequate, but should be modified to include new configuration files for certain applications. I would recommend merging the configuration files from here: https://nebulacentre.net/dotfiles/taroumaru into the current repo before the next release.

**Comment by tonijarjour** [comment]
Can you be more specific about what you want me to add? The config files of this program are deliberately sparse so that users can easily understand and customize them to their preferences. 
Adding large amount of stuff, that one person probably made for himself, is counter to the goal here.

**Comment by nebulaw2081d** [comment]
I guess you could be right. I would rather not argue with a maintainer. I will fork it and merge the files myself.
